[package]
name = "discord_client_utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
discord_client_structs = { path = "../discord_client_structs" }
rquest = { workspace = true, features = ["gzip", "deflate", "zstd", "brotli", "json", "cookies"] }
rquest-util = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }